CREATE TABLE EVENT (
	EVENT_ID INT IDENTITY,
	EVENT_NAME VARCHAR(50) NOT NULL,
	VENUE VARCHAR(50) NOT NULL,
	SLOT_AVAILABLE INT NOT NULL
);

CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT IDENTITY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL_ID VARCHAR(100) NOT NULL,
	EVENT_DATE DATE NOT NULL,
	EVENT_NAME VARCHAR(100) NOT NULL,
	EVENT_ID INT
);

INSERT INTO EVENT(EVENT_ID, EVENT_NAME, VENUE, SLOT_AVAILABLE) VALUES (1011, 'Meeting', 'ConferenceCentre',  3);
INSERT INTO EVENT(EVENT_ID, EVENT_NAME, VENUE, SLOT_AVAILABLE) VALUES (1012, 'Concert', 'Arena', 1);
INSERT INTO EVENT(EVENT_ID, EVENT_NAME, VENUE, SLOT_AVAILABLE) VALUES (1013, 'Workshop', 'AcademicVENUE', 2);

INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1001, 'Jake', 'jake@abc.com', '2021-11-28', 'Meeting', 1011);
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1002, 'Mary', 'mary@abc.com', '2022-05-10', 'Concert', 1012);
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1003, 'Kenny', 'kenny@abc.com', '2022-02-17', 'Workshop',  1013);
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1004, 'Brad', 'brad@abc.com', '2021-11-10', 'Meeting', 1011);
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1005, 'Alice', 'alice@abc.com', '2021-12-13', 'Workshop',  1013);
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1006, 'Smith', 'smith@abc.com', '2021-11-09', 'Concert', 1012);
INSERT INTO CUSTOMER(CUSTOMER_ID, NAME, EMAIL_ID,  EVENT_DATE, EVENT_NAME,  EVENT_ID) VALUES (1007, 'John', 'john@abc.com', '2022-03-25', 'Concert',1012);